Feature/696
eyra/mono pull request #992
Opened 2024-11-07 12:46 UTC by MelchiorKokernoot

2024-11-07 12:47 UTC, MelchiorKokernoot commented on core/frameworks/pixel/components/button.ex
> +  # deprecated "Use button.dynamic instead"
```suggestion
```

2024-11-13 23:00 UTC, mellelieuwes requested changes

2024-11-14 09:51 UTC, MelchiorKokernoot commented on core/frameworks/pixel/components/file_selector.ex
> +              <div class="cursor-pointer pt-15px pb-15px active:shadow-top4px active:pt-4 active:pb-14px leading-none font-button text-button focus:outline-none rounded pr-4 pl-4 bg-tertiary text-gre
Geïmplementeerd!

2024-11-14 10:04 UTC, mellelieuwes approved these changes

2024-11-14 10:05 UTC, merged

2024-12-12 09:14 UTC, MelchiorKokernoot commented
Deze is waarschijnlijk niet goed meegekomen met de release, we zullen hem nog een. Ik geloof dat hij nu wel in develop zit maar ik weet niet zeker of develop in zijn volledigheid is meegekomen met de vorige release. Even controleren of hij in develop zit, en zo ja zal hij dan waarschijnlijk meekomen met de volgende release